import { reactive, watch } from 'vue'

const savedLanguage = typeof window !== 'undefined' ? window.localStorage.getItem('idol-language') : null

export const state = reactive({
  lang: savedLanguage === 'en' ? 'en' : 'zh',
  store: null,
  wechat: false,
  bookingEnabled: false
})

if (typeof document !== 'undefined') document.documentElement.lang = state.lang === 'en' ? 'en' : 'zh-CN'

watch(() => state.lang, (language) => {
  if (typeof window !== 'undefined') {
    window.localStorage.setItem('idol-language', language)
    document.documentElement.lang = language === 'en' ? 'en' : 'zh-CN'
  }
})

export const translations = {
  zh: {
    nav_home: '首页',
    nav_highlights: '拼豆精选',
    nav_pricing: '价位表',
    nav_booking: '预约体验',
    nav_social: '社交媒体',
    nav_member_center: '会员中心',
    nav_account: '我的账号',
    nav_lookup: '查询预约',
    nav_login: '登录',
    nav_register: '注册',
    brand_home_label: 'IDOL BEADS 首页',
    mobile_menu_label: '打开导航',
    language_switch_label: '切换语言',
    hero_desc: '拼豆工作室',
    hero_slogan: 'IDOL BEADS， 与快乐同行',
    cta_booking: '预约体验',
    cta_pricing: '查看价位',
    reviews_title: 'IDOL BEADS 顾客评价',
    member_title: '会员专享福利',
    member_rule_1: '会员月卡 $19.90 SGD，年卡 $149 SGD',
    member_rule_2: '每件作品赠送 1 份 DIY 饰品，不限作品数量',
    member_rule_3: '会员到店消费享 8 折优惠',
    feat1_title: '专业烫印',
    feat1_desc: '店内使用全自动烫画机和手持烫画机，提供 30 多种特殊烫。工作人员会帮你完成最后的烫步骤，尽力做好作品。',
    feat2_title: '免费工具',
    feat2_desc: '店内工具齐全，全尺寸双九华长钉板，配备弯/直头镊子、多规格道豆铲、立豆盘、挖豆勺。还有市面上有口皆碑的单针、双针（60 针、70 针、80 针、陶瓷针），以及生煎包自动下豆笔。',
    feat3_title: 'DIY 成品',
    feat3_desc: '成品可做钥匙扣、冰箱贴、卡包、护照夹、扇子，并提供轴承、支架等配件。',
    feat4_title: '小红书集赞赢会员',
    feat4_desc: '在小红书发布本店作品、体验或探店内容，带上话题 #IDOL Beads #新加坡拼豆 并 @IDOL Beads。集满 30/60/100 及以上赞，分别赠送 1/2/3 个月会员资格。仅限本店顾客、公开笔记，每个账号每月限参与 1 次，集赞达标后截图给店员核对，活动最终解释权归本店所有。',
    highlights_title: '拼豆精选',
    btn_view_details: '查看详情',
    highlights_page_kicker: 'BEAD CREATIONS',
    highlights_page_title: '拼豆作品集',
    highlights_page_desc: '从萌趣小物到人气角色，在这里找到你的下一个拼豆灵感。',
    highlights_gallery_label: '全部作品',
    highlights_gallery_count: '件创意作品',
    highlights_book_title: '找到想做的款式了吗？',
    highlights_book_desc: '到店挑选图纸和颜色，亲手完成你的专属作品。',
    highlights_book_button: '预约拼豆体验',
    highlights_back_home: '返回首页',
    studio_location: '牛车水解压手工好去处 · 适合放空与朋友小聚',
    pricing_title: '价位表',
    pricing_card_title: '价位表 · Pricing',
    pricing_note_title: '备注 · Note',
    pricing_note_membership: '会员 Membership: $19.90 SGD/月 (month)，$149 SGD/年 (year)。',
    pricing_note_benefits: '会员福利 Member benefits: 每件作品可获赠 1 份 DIY 饰品，不限作品数量；到店消费享 8 折优惠。',
    pricing_note_group: '多人同行 Group rate: 两人及以上同行，非会员按多人同行价；同行里有会员，该会员按会员价计算。',
    pricing_note_weekend: '周末及节假日 Weekends & public holidays: 所有价格加收 10% 服务费。',
    hourly_pricing: '按时计费',
    daypass_pricing: '全天通票',
    th_people: '人数',
    th_price: '价格',
    pricing_th_duration: '时长',
    pricing_th_single: '单人',
    pricing_th_member: '会员（八折）',
    pricing_th_group: '多人同行 2人以上（九折）',
    pricing_duration_one: '1 小时',
    pricing_duration_six: '6 小时',
    pricing_duration_day: '全天不限时',
    td_solo_label: '单人',
    td_duo_label: '双人',
    th_date: '日期',
    td_wed_thu: '周三 - 周四',
    td_fri_sun: '周五 - 周日',
    booking_title: '预约体验',
    booking_closed_title: '预约暂未开放',
    booking_closed_desc: '门店正在筹备中，线上预约开放后我们会第一时间更新。感谢你的理解与耐心等待。',
    label_date_select: '选择日期',
    label_time_select: '到店时间',
    label_duration_select: '预期消费时长',
    label_people_select: '预约人数',
    label_table_select: '选择桌位',
    table_select_hint: '先选择人数，再选择可容纳当前人数的桌位；选桌后查看可约时间。',
    table_select_time_first: '请先选择合适的桌位',
    table_loading: '正在读取桌位状态…',
    table_available: '可选择',
    table_selected: '已选择',
    table_occupied: '已占用',
    table_empty: '暂无符合人数且有可约时段的桌位',
    table_slot_count: '{count} 个可约时段',
    table_all_day_available: '全天可约',
    time_capacity: '可预约 · {count} 张桌可用',
    time_capacity_one: '可预约 · 1 张桌可用',
    time_full: '已占用',
    label_personal_info: '填写预约信息',
    unit_min: '分钟',
    unit_hour: '小时',
    unit_person: '人',
    unit_person_one: '人',
    people_note: '多人预约将由门店自动组合安排桌位。',
    opt_daypass: '全天通票',
    opt_one_hour: '1 小时',
    opt_six_hours: '6 小时',
    opt_custom_duration: '自定义时长',
    custom_duration_label: '预约时长',
    custom_duration_hint: '请输入 1–{max} 小时的整数时长',
    custom_duration_value: '{count} 小时',
    opt_custom_people: '自定义人数',
    custom_people_label: '预约人数',
    custom_people_hint: '最多可填写 {max} 人，门店将自动安排桌位',
    btn_confirm: '确认预约',
    btn_submitting: '提交中...',
    btn_review_booking: '核对预约信息',
    booking_review_title: '请确认预约信息',
    booking_review_tip: '请核对日期、时间和人数。提交后由门店确认，确认成功会发送邮件。',
    booking_review_date: '日期',
    booking_review_time: '时间',
    booking_review_duration: '套餐',
    booking_review_people: '人数',
    booking_review_tables: '桌位安排',
    booking_table_auto: '门店后台自动安排',
    booking_pending_email_tip: '提交后等待门店确认，确认成功后将收到邮件。',
    booking_review_contact: '联系人',
    booking_review_cancel: '返回修改',
    booking_review_submit: '确认并提交预约',
    booking_validation_personal: '请填写姓名、电话和邮箱',
    booking_validation_phone: '请输入正确的新加坡手机号，例如 +65 8123 4567',
    booking_validation_email: '请输入正确的邮箱地址，例如 name@example.com',
    booking_validation_time: '请选择到店时间',
    booking_validation_tables: '请先选择足够容纳当前人数的桌位',
    booking_validation_availability: '当前时段已无合适桌位，请选择其他时间',
    placeholder_name: '您的姓名',
    placeholder_phone: '手机号，例如 +65 8123 4567',
    placeholder_email: '你的邮箱',
    placeholder_notes: '特别说明',
    success_title: '✓ 预约申请已提交！',
    success_desc: '门店确认后预约才会生效，确认成功后将发送邮件，请留意收件箱。',
    booking_code_label: '预约码',
    booking_view_account: '查看我的预约',
    back_home: '返回首页',
    error_title: '⚠️ 提交失败',
    error_desc: '抱歉，预约提交时出现问题。请稍后再试或通过社交媒体联系我们。',
    social_xhs: '小红书',
    social_wechat: '微信公众号',
    footer_location_title: '店铺地址',
    footer_social_title: '社交媒体',
    footer_hours_title: '营业时间',
    footer_hours_note: '全年无休，公共假期正常营业',
    footer_directions_title: '如何找到我们',
    footer_directions_address: '18A Sago Street, Singapore 059017 · 门店位于二楼，请从临街楼梯上楼。',
    footer_directions_guide: '查看小红书图文到店指南',
    footer_route_maxwell_exit: '1号出口',
    footer_route_maxwell_step_1: '出站后朝佛牙寺方向步行。',
    footer_route_maxwell_step_2: '右转进入 Sago Street，找到 18A 门牌。',
    footer_route_maxwell_step_3: '从临街楼梯上二楼即可到达 IDOL Beads。',
    footer_route_chinatown_exit: 'A出口',
    footer_route_chinatown_step_1: '沿 Pagoda Street 直走，经过马里安曼兴都庙。',
    footer_route_chinatown_step_2: '沿 South Bridge Road 朝佛牙寺方向前行，再转入 Sago Street。',
    footer_route_chinatown_step_3: '找到 18A 门牌，从楼梯上二楼到店。',
    social_douyin: '抖音',
    booking_page_title: '预约 IDOL BEADS',
    booking_page_desc: '无需登录，填写邮箱即可预约；已有账号会自动关联到你的预约记录。',
    not_found_title: '页面走丢了',
    not_found_desc: '这个链接已经不存在，返回首页继续浏览吧。',
    promo_carousel_label: '活动图片轮播',
    promo_previous: '上一张图片',
    promo_next: '下一张图片',
    promo_navigation: '轮播图导航',
    promo_show_slide: '显示第 {count} 张图片',
    gallery_close: '关闭',
    gallery_previous: '上一张',
    gallery_next: '下一张',
    auth_visual_title: '把灵感拼成喜欢的样子',
    auth_back_home: '返回首页',
    auth_login_title: '登录账号',
    auth_register_title: '创建账号',
    auth_login_desc: '登录后查看你的预约与会员信息。',
    auth_register_desc: '验证邮箱后即可完成注册。',
    auth_account_label: '用户名或邮箱',
    auth_account_placeholder: '请输入用户名或邮箱',
    auth_username_label: '用户名',
    auth_username_placeholder: '2–30 位字母、数字或下划线',
    auth_email_label: '邮箱',
    auth_code_label: '邮箱验证码',
    auth_code_placeholder: '6 位验证码',
    auth_code_valid: '验证码 10 分钟内有效',
    auth_code_sent: '验证码已发送，请检查收件箱和垃圾邮件',
    auth_get_code: '获取验证码',
    auth_sending: '发送中…',
    auth_password_label: '密码',
    auth_password_placeholder: '至少 6 位',
    auth_wait: '请稍候…',
    auth_login_button: '登录',
    auth_register_button: '注册并登录',
    auth_no_account: '还没有账号？',
    auth_has_account: '已经有账号？',
    auth_register_now: '立即注册',
    auth_go_login: '去登录',
    auth_booking_question: '只想预约？',
    auth_booking_direct: '无需登录，直接预约',
    auth_invalid_email: '请先填写正确的邮箱地址',
    auth_code_failed: '验证码发送失败',
    auth_login_failed: '登录失败',
    auth_register_failed: '注册失败',
    account_title: '我的账号',
    account_lookup_title: '查询预约',
    account_desc: '在这里查看账号资料和全部预约记录。',
    account_lookup_desc: '无需登录，使用预约手机号和邮箱即可查看预约详情。',
    account_loading: '正在加载…',
    account_lookup_heading: '查找我的预约',
    account_lookup_help: '请输入提交预约时填写的手机号和邮箱，两项信息匹配后即可查看预约。',
    account_booking_email: '预约邮箱',
    account_booking_phone: '预约手机号',
    account_phone_placeholder: '例如 +65 8123 4567',
    account_searching: '正在查询…',
    account_lookup_button: '查询预约',
    account_result_title: '预约详情',
    account_people_unit: '人',
    account_booking_code: '预约码',
    account_member_booking: '会员预约',
    account_registered: '已经注册账号？',
    account_login_all: '登录后查看全部预约',
    account_no_booking_question: '还没有预约？',
    account_book_now: '立即预约体验',
    account_standard_user: '普通用户',
    account_book_again: '再次预约',
    account_logout: '退出登录',
    member_expired: '会员已到期',
    member_join_title: '加入 IDOL BEADS 会员',
    member_number: '会员号',
    member_valid_until: '有效期至',
    member_intro: '开通会员可享会员价与专属权益，到店付款后由门店确认开通。',
    member_benefit_price: '预约自动使用会员价',
    member_benefit_gift: '每件作品赠送 DIY 饰品',
    member_benefit_discount: '到店消费享会员折扣',
    member_pending_title: '开通申请待门店确认',
    member_pay_in_store: '请到店付款',
    member_days: '天',
    member_submitting: '提交中…',
    member_renew: '申请续费',
    member_apply: '申请开通',
    reservations_title: '我的预约',
    reservations_empty_title: '还没有预约',
    reservations_empty_desc: '选一个喜欢的时间，来工作室慢慢拼一件作品吧。',
    reservations_closed_desc: '线上预约暂未开放，开放后即可在这里预约体验。',
    reservations_book_now: '现在预约',
    status_pending: '待确认',
    status_booked: '已预约',
    status_checked_in: '已核销',
    status_in_service: '体验中',
    status_completed: '已完成',
    status_cancelled: '已取消',
    account_load_failed: '页面加载失败',
    appointments_load_failed: '预约记录加载失败',
    lookup_failed: '预约查询失败，请稍后再试',
    membership_load_failed: '会员信息加载失败',
    membership_request_failed: '会员申请提交失败',
    membership_confirm_request: '申请{plan}，金额 S${price}，到店付款后由门店确认开通？',
    member_level_default: '手作会员',
    member_plan_monthly: '月卡会员',
    member_plan_annual: '年卡会员',
    member_plan_benefit_discount: '全场消费享会员八折优惠',
    wechat_scan_tip: '扫一扫，关注我们的微信公众号',
    today: '今天',
    tomorrow: '明天',
    mon: '周一', tue: '周二', wed: '周三', thu: '周四', fri: '周五', sat: '周六', sun: '周日'
  },
  en: {
    nav_home: 'Home',
    nav_highlights: 'Gallery',
    nav_pricing: 'Pricing',
    nav_booking: 'Booking',
    nav_social: 'Social',
    nav_member_center: 'Member Center',
    nav_account: 'My Account',
    nav_lookup: 'Find Booking',
    nav_login: 'Log In',
    nav_register: 'Sign Up',
    brand_home_label: 'IDOL BEADS home',
    mobile_menu_label: 'Open navigation',
    language_switch_label: 'Switch language',
    hero_desc: 'Perler Bead Workshop',
    hero_slogan: 'IDOL BEADS, joy every step of the way',
    cta_booking: 'Book Now',
    cta_pricing: 'View Pricing',
    reviews_title: 'IDOL BEADS Customer Reviews',
    member_title: 'Member Benefits',
    member_rule_1: 'S$19.90 monthly membership · S$149 annual membership',
    member_rule_2: 'One free DIY accessory with every piece, no quantity limit',
    member_rule_3: 'Members enjoy 20% off in-store purchases',
    feat1_title: 'Professional Ironing',
    feat1_desc: 'We use both automatic and handheld heat presses, with over 30 special ironing finishes available. Our team will complete the final ironing steps and do their best to finish your creation beautifully.',
    feat2_title: 'Free Tools',
    feat2_desc: 'Our complete tool selection includes full-size Shuangjiuhua long-peg boards, angled and straight tweezers, bead scoops in multiple sizes, upright bead trays and bead spoons. Popular tools include single-needle and dual-needle pens (60, 70, 80 and ceramic needles), plus Shengjianbao automatic bead dispensers.',
    feat3_title: 'DIY Finished Pieces',
    feat3_desc: 'Turn your creation into a keyring, fridge magnet, card holder, passport holder or fan, with bearings, stands and other accessories also available.',
    feat4_title: 'RedNote Likes for Membership',
    feat4_desc: 'Post your creation, studio experience or store visit on RedNote with #IDOL Beads, #SingaporePerlerBeads and @IDOL Beads. Earn 30, 60, or 100+ likes to receive 1, 2, or 3 months of membership. Open to IDOL Beads customers with public posts; one redemption per account each month. Show a screenshot to our team once your likes reach the target. Final interpretation of the promotion rests with the studio.',
    highlights_title: 'Perler Bead Highlights',
    btn_view_details: 'View Details',
    highlights_page_kicker: 'BEAD CREATIONS',
    highlights_page_title: 'Bead Creations Gallery',
    highlights_page_desc: 'From adorable miniatures to beloved characters, find inspiration for your next bead creation.',
    highlights_gallery_label: 'All Creations',
    highlights_gallery_count: 'creative pieces',
    highlights_book_title: 'Found something you would love to make?',
    highlights_book_desc: 'Choose your pattern and colors in store, then bring your own creation to life.',
    highlights_book_button: 'Book a Beading Session',
    highlights_back_home: 'Back to Home',
    studio_location: 'A relaxing Chinatown craft spot · Perfect for unwinding and meeting friends',
    pricing_title: 'Pricing',
    pricing_card_title: 'Pricing',
    pricing_note_title: 'Notes',
    pricing_note_membership: 'Membership: S$19.90/month or S$149/year.',
    pricing_note_benefits: 'Member benefits: One free DIY accessory with every piece, plus 20% off in-store purchases.',
    pricing_note_group: 'Group rate: For 2 or more guests, non-members pay the group rate and members pay the member rate.',
    pricing_note_weekend: 'Weekends & public holidays: A 10% service charge applies to all prices.',
    hourly_pricing: 'Hourly Rate',
    daypass_pricing: 'Day Pass',
    th_people: 'People',
    th_price: 'Price',
    pricing_th_duration: 'Duration',
    pricing_th_single: 'Single',
    pricing_th_member: 'Member (20% Off)',
    pricing_th_group: 'Group 2+ (10% Off)',
    pricing_duration_one: '1-Hour Session',
    pricing_duration_six: '6-Hour Session',
    pricing_duration_day: 'Full-Day Pass',
    td_solo_label: 'Solo',
    td_duo_label: 'Duo',
    th_date: 'Date',
    td_wed_thu: 'Wed - Thu',
    td_fri_sun: 'Fri - Sun',
    booking_title: 'Book a Session',
    booking_closed_title: 'Online Booking Coming Soon',
    booking_closed_desc: 'We are getting the studio ready. Online booking will open soon—thank you for your patience.',
    label_date_select: 'Select Date',
    label_time_select: 'Arrival Time',
    label_duration_select: 'Expected Duration',
    label_people_select: 'Number of People',
    label_table_select: 'Choose Seats',
    table_select_hint: 'Choose your party size first, then select a table to see its available times.',
    table_select_time_first: 'Choose a suitable table first',
    table_loading: 'Loading seat availability…',
    table_available: 'Available',
    table_selected: 'Selected',
    table_occupied: 'Occupied',
    table_empty: 'No suitable tables have available times',
    table_slot_count: '{count} available times',
    table_all_day_available: 'All day available',
    time_capacity: 'Available · {count} tables',
    time_capacity_one: 'Available · 1 table',
    time_full: 'Unavailable',
    label_personal_info: 'Your Details',
    unit_min: 'min',
    unit_hour: 'hours',
    unit_person: 'people',
    unit_person_one: 'person',
    people_note: 'For larger groups, the studio will automatically combine tables.',
    opt_daypass: 'All-Day Pass',
    opt_one_hour: '1 Hour',
    opt_six_hours: '6 Hours',
    opt_custom_duration: 'Custom Duration',
    custom_duration_label: 'Duration',
    custom_duration_hint: 'Enter a whole number from 1 to {max} hours',
    custom_duration_value: '{count} Hours',
    opt_custom_people: 'Custom Guests',
    custom_people_label: 'Number of guests',
    custom_people_hint: 'Up to {max} guests; tables will be assigned automatically',
    btn_confirm: 'Confirm',
    btn_submitting: 'Submitting...',
    btn_review_booking: 'Review Booking',
    booking_review_title: 'Confirm Your Booking',
    booking_review_tip: 'Please check the date, time, and party size. The studio will confirm your request by email.',
    booking_review_date: 'Date',
    booking_review_time: 'Time',
    booking_review_duration: 'Session',
    booking_review_people: 'Guests',
    booking_review_tables: 'Table',
    booking_table_auto: 'Assigned automatically by the studio',
    booking_pending_email_tip: 'The studio will review your request and email you once it is confirmed.',
    booking_review_contact: 'Contact',
    booking_review_cancel: 'Go Back',
    booking_review_submit: 'Confirm & Book',
    booking_validation_personal: 'Please enter your name, phone number, and email',
    booking_validation_phone: 'Enter a valid Singapore mobile number, e.g. +65 8123 4567',
    booking_validation_email: 'Enter a valid email address, e.g. name@example.com',
    booking_validation_time: 'Please select an arrival time',
    booking_validation_tables: 'Please select enough tables for your party first',
    booking_validation_availability: 'No suitable table is available at this time. Please choose another time',
    placeholder_name: 'Your Name',
    placeholder_phone: 'Mobile, e.g. +65 8123 4567',
    placeholder_email: 'Email for confirmation',
    placeholder_notes: 'Special Instructions',
    success_title: '✓ Booking Request Submitted!',
    success_desc: 'Your booking becomes active after studio confirmation. A confirmation email will be sent to you.',
    booking_code_label: 'Booking Code',
    booking_view_account: 'View My Bookings',
    back_home: 'Back to Home',
    error_title: '⚠️ Submission Failed',
    error_desc: 'Sorry, there was a problem. Please try again later.',
    social_xhs: 'RedNote',
    social_wechat: 'WeChat',
    footer_location_title: 'Our Location',
    footer_social_title: 'Social Media',
    footer_hours_title: 'Opening Hours',
    footer_hours_note: 'Open daily, including public holidays',
    footer_directions_title: 'How to Find Us',
    footer_directions_address: '18A Sago Street, Singapore 059017 · We are on level 2; take the street-facing stairs.',
    footer_directions_guide: 'View the illustrated RedNote guide',
    footer_route_maxwell_exit: 'Exit 1',
    footer_route_maxwell_step_1: 'Walk towards the Buddha Tooth Relic Temple.',
    footer_route_maxwell_step_2: 'Turn right into Sago Street and look for No. 18A.',
    footer_route_maxwell_step_3: 'Take the street-facing stairs to IDOL Beads on level 2.',
    footer_route_chinatown_exit: 'Exit A',
    footer_route_chinatown_step_1: 'Walk along Pagoda Street and pass Sri Mariamman Temple.',
    footer_route_chinatown_step_2: 'Continue along South Bridge Road towards the Buddha Tooth Relic Temple, then turn into Sago Street.',
    footer_route_chinatown_step_3: 'Find No. 18A and take the stairs to the studio on level 2.',
    social_douyin: 'TikTok',
    booking_page_title: 'Book IDOL BEADS',
    booking_page_desc: 'No login required. Book with your email, or sign in to link the booking to your account.',
    not_found_title: 'Page Not Found',
    not_found_desc: 'This page no longer exists. Head back home to keep exploring.',
    promo_carousel_label: 'Promotional image carousel',
    promo_previous: 'Previous image',
    promo_next: 'Next image',
    promo_navigation: 'Carousel navigation',
    promo_show_slide: 'Show image {count}',
    gallery_close: 'Close',
    gallery_previous: 'Previous image',
    gallery_next: 'Next image',
    auth_visual_title: 'Turn inspiration into something you love',
    auth_back_home: 'Back to Home',
    auth_login_title: 'Log In',
    auth_register_title: 'Create Account',
    auth_login_desc: 'Log in to view your bookings and membership.',
    auth_register_desc: 'Verify your email to finish creating your account.',
    auth_account_label: 'Username or Email',
    auth_account_placeholder: 'Enter your username or email',
    auth_username_label: 'Username',
    auth_username_placeholder: '2–30 letters, numbers, or underscores',
    auth_email_label: 'Email',
    auth_code_label: 'Email Verification Code',
    auth_code_placeholder: '6-digit code',
    auth_code_valid: 'The verification code is valid for 10 minutes',
    auth_code_sent: 'Code sent. Please check your inbox and spam folder.',
    auth_get_code: 'Get Code',
    auth_sending: 'Sending…',
    auth_password_label: 'Password',
    auth_password_placeholder: 'At least 6 characters',
    auth_wait: 'Please wait…',
    auth_login_button: 'Log In',
    auth_register_button: 'Sign Up & Log In',
    auth_no_account: 'New to IDOL BEADS?',
    auth_has_account: 'Already have an account?',
    auth_register_now: 'Sign Up',
    auth_go_login: 'Log In',
    auth_booking_question: 'Just want to book?',
    auth_booking_direct: 'Book directly without logging in',
    auth_invalid_email: 'Enter a valid email address first',
    auth_code_failed: 'Could not send the verification code',
    auth_login_failed: 'Login failed',
    auth_register_failed: 'Registration failed',
    account_title: 'My Account',
    account_lookup_title: 'Find a Booking',
    account_desc: 'View your profile, membership, and all bookings here.',
    account_lookup_desc: 'No login required. Use the mobile number and email from your booking.',
    account_loading: 'Loading…',
    account_lookup_heading: 'Find My Booking',
    account_lookup_help: 'Enter the same mobile number and email used when making the booking.',
    account_booking_email: 'Booking Email',
    account_booking_phone: 'Booking Mobile',
    account_phone_placeholder: 'e.g. +65 8123 4567',
    account_searching: 'Searching…',
    account_lookup_button: 'Find Booking',
    account_result_title: 'Booking Details',
    account_people_unit: 'guests',
    account_booking_code: 'Booking Code',
    account_member_booking: 'Member Booking',
    account_registered: 'Already registered?',
    account_login_all: 'Log in to view all bookings',
    account_no_booking_question: 'No booking yet?',
    account_book_now: 'Book a Session',
    account_standard_user: 'Standard Account',
    account_book_again: 'Book Again',
    account_logout: 'Log Out',
    member_expired: 'Membership Expired',
    member_join_title: 'Join IDOL BEADS Membership',
    member_number: 'Member No.',
    member_valid_until: 'Valid until',
    member_intro: 'Enjoy member pricing and exclusive perks. Pay in store and our team will activate your membership.',
    member_benefit_price: 'Member pricing applied automatically',
    member_benefit_gift: 'One free DIY accessory with every piece',
    member_benefit_discount: 'Member discount on in-store purchases',
    member_pending_title: 'Membership Request Awaiting Confirmation',
    member_pay_in_store: 'Pay in store',
    member_days: 'days',
    member_submitting: 'Submitting…',
    member_renew: 'Request Renewal',
    member_apply: 'Apply Now',
    reservations_title: 'My Bookings',
    reservations_empty_title: 'No Bookings Yet',
    reservations_empty_desc: 'Choose a time and spend a relaxing session creating something you love.',
    reservations_closed_desc: 'Online booking is not open yet. You can book here once it launches.',
    reservations_book_now: 'Book Now',
    status_pending: 'Pending Confirmation',
    status_booked: 'Confirmed',
    status_checked_in: 'Checked In',
    status_in_service: 'In Session',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    account_load_failed: 'Could not load this page',
    appointments_load_failed: 'Could not load your bookings',
    lookup_failed: 'Could not find the booking. Please try again.',
    membership_load_failed: 'Could not load membership details',
    membership_request_failed: 'Could not submit the membership request',
    membership_confirm_request: 'Apply for {plan} at S${price}? Pay in store and our team will activate it.',
    member_level_default: 'IDOL BEADS Member',
    member_plan_monthly: 'Monthly Membership',
    member_plan_annual: 'Annual Membership',
    member_plan_benefit_discount: '20% off all in-store purchases',
    wechat_scan_tip: 'Scan to follow our WeChat Account',
    today: 'Today',
    tomorrow: 'Tomorrow',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun'
  }
}

export function t(key) {
  const override = state.store?.siteContent?.translations?.[state.lang]?.[key]
  return typeof override === 'string' ? override : (translations[state.lang]?.[key] ?? key)
}

export function siteMedia(key, fallback = null) {
  const value = state.store?.siteContent?.media?.[key]
  return value == null || value === '' ? fallback : value
}

export function siteLink(key, fallback = '') {
  const value = state.store?.siteContent?.links?.[key]
  return typeof value === 'string' ? value : fallback
}

export function fmtPrice(n) {
  if (n == null || n === '' || Number.isNaN(Number(n))) return '—'
  return '$' + Number(n).toFixed(2).replace(/\.?0+$/, '')
}

export function addMinutes(hhmm, mins) {
  const [h, m] = hhmm.split(':').map(Number)
  const total = h * 60 + m + mins
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`
}

export async function loadStore() {
  const [storeResult, statusResult] = await Promise.allSettled([
    fetch('/api/stores/1'),
    fetch('/api/appointments/status')
  ])
  if (storeResult.status === 'fulfilled' && storeResult.value.ok) {
    state.store = await storeResult.value.json()
  }
  if (statusResult.status === 'fulfilled' && statusResult.value.ok) {
    const status = await statusResult.value.json()
    state.bookingEnabled = status.enabled === true
  } else {
    state.bookingEnabled = false
  }
  if (state.store?.name) {
    const configuredTitle = state.store.siteContent?.meta?.title
    document.title = configuredTitle || `${state.store.name} | DIY Bead Workshop`
    const description = state.store.siteContent?.meta?.description
    if (description) {
      let meta = document.querySelector('meta[name="description"]')
      if (!meta) {
        meta = document.createElement('meta')
        meta.name = 'description'
        document.head.appendChild(meta)
      }
      meta.content = description
    }
  }
  return state.store
}

export async function fetchAvailability(date) {
  const r = await fetch(`/api/appointments/availability?storeId=1&date=${date}`)
  if (!r.ok) throw new Error('Availability request failed')
  return r.json()
}

export function createAppointment(dto) {
  return fetch('/api/appointments', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dto)
  })
}

export const featuredHighlights = [
  { src: 'photos/xhs-studio.jpg', altZh: 'IDOL BEADS 拼豆工作室', altEn: 'IDOL BEADS studio' },
  { src: 'photos/xhs-character-wall.jpg', altZh: '拼豆角色作品墙', altEn: 'Perler bead character creations' },
  { src: 'photos/xhs-display-wall.jpg', altZh: '拼豆作品展示墙', altEn: 'Perler bead creation display' }
]

export const allHighlights = [
  'photos/xhs-bead-colors.jpg',
  'photos/xhs-price-list.jpg',
  'photos/show_27.jpg',
  'photos/show_28.jpg',
  'photos/show_29.jpg',
  'photos/show_4.jpg',
  'photos/show_5.jpg',
  'photos/show_6.jpg',
  'photos/show_7.jpg',
  'photos/show_8.jpg',
  'photos/show_9.jpg',
  'photos/show_10.jpg',
  'photos/show_11.jpg',
  'photos/show_12.jpg',
  'photos/show_13.jpg',
  'photos/show_14.jpg',
  'photos/show_15.jpg',
  'photos/show_16.jpg',
  'photos/show_17.jpg',
  'photos/show_18.jpg',
  'photos/show_19.jpg',
  'photos/show_20.jpg',
  'photos/show_21.jpg',
  'photos/show_22.jpg',
  'photos/show_23.jpg',
  'photos/微信图片_20260411232112.jpg',
  'photos/微信图片_20260411232124.jpg',
  'photos/微信图片_20260411232130.jpg',
  'photos/微信图片_20260411232135.jpg',
  'photos/微信图片_20260411232139.jpg',
  'photos/微信图片_20260411232144.jpg',
  'photos/微信图片_20260411232150.jpg',
  'photos/微信图片_20260411232155.jpg',
  'photos/微信图片_20260411232159.jpg',
  'photos/微信图片_20260411232204.jpg',
  'photos/微信图片_20260411232208.jpg',
  'photos/微信图片_20260411232215.jpg',
  'photos/微信图片_20260411232219.jpg',
  'photos/微信图片_20260411232222.jpg',
  'photos/微信图片_20260411232227.jpg',
  'photos/微信图片_20260411232231.jpg',
  'photos/微信图片_20260411232250.jpg',
  'photos/微信图片_20260411232255.jpg',
  'photos/微信图片_20260411232258.jpg',
  'photos/微信图片_20260411232304.jpg',
  'photos/微信图片_20260411232315.jpg',
  'photos/微信图片_20260411232319.jpg',
  'photos/微信图片_20260411232323.jpg',
  'photos/微信图片_20260411232327.jpg',
  'photos/微信图片_20260411232331.jpg',
  'photos/微信图片_20260411232335.jpg',
  'photos/微信图片_20260411232338.jpg',
  'photos/微信图片_20260411232341.jpg',
  'photos/微信图片_20260411232345.jpg',
  'photos/微信图片_20260411232350.jpg',
  'photos/微信图片_20260411232354.jpg'
]

export const defaultReviews = [
  {
    image: '/photos/xhs-studio.jpg',
    altZh: 'IDOL Beads 宽敞明亮的拼豆工作室',
    quoteZh: '终于在新加坡找到环境舒服、桌面宽敞的拼豆店。工作日可以直接 walk in，安排起来很方便。',
    altEn: 'The bright and spacious IDOL Beads studio',
    quoteEn: 'A bright, comfortable bead studio in Singapore with plenty of workspace. Weekday walk-ins make it especially easy to visit.'
  },
  {
    image: '/photos/xhs-character-wall.jpg',
    altZh: 'IDOL Beads 顾客拼豆作品展示墙',
    quoteZh: '牛车水里的宝藏拼豆店，特殊烫款式很丰富，涵盖市面上常见的 30 多种特殊烫，选图的时候就已经很快乐。',
    altEn: 'Customer bead creations displayed at IDOL Beads',
    quoteEn: 'A Chinatown gem with an extensive range of special ironing styles, including more than 30 popular finishes. Choosing a design is part of the fun.'
  },
  {
    image: '/photos/xhs-display-wall.jpg',
    altZh: 'IDOL Beads 拼豆作品与工具陈列',
    quoteZh: '从豆板、豆铲到豆针都好看又顺手，颜色摆放清楚，慢慢拼一下午也很放松。',
    altEn: 'Bead creations and tools displayed at IDOL Beads',
    quoteEn: 'The boards, scoops, pens and neatly arranged colours are lovely to use—a relaxing place to spend a creative afternoon.'
  }
]

export const defaultSiteMedia = {
  logo: '/photos/idol-logo.png',
  heroBackground: '/photos/hero-studio.jpg',
  banners: ['/photos/banner-floor-2.png', '/photos/banner-floor-1.png'],
  featureIcons: [1, 2, 3, 4].map((n) => `/photos/feat-icon-${n}.png`),
  featuredHighlights: featuredHighlights.map((item) => `/${item.src}`),
  galleryImages: [
    ...featuredHighlights.map((item) => `/${item.src}`),
    ...allHighlights
      .filter((src) => src !== 'photos/xhs-price-list.jpg')
      .map((src) => `/${src}`)
  ]
}
